version: "3"
services:
  udpsender1:
    build:
      context: .
      dockerfile: DockerfileUdpSender
    volumes:
      - C:\Temp\UdpCommunication\UdpSender:/opt/mm/udpsender
    networks:
      static-network:
        ipv4_address: 172.21.0.2
  udpsender2:
    build:
      context: .
      dockerfile: DockerfileUdpSender
    volumes:
      - C:\Temp\UdpCommunication\UdpSender:/opt/mm/udpsender
    networks:
      static-network:
        ipv4_address: 172.21.0.3
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.21.0.0/16